import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Load a custom font.
Font.register({
  family: 'Poppins',
  src: 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap',
});

// Define styles for the PDF document
const styles = StyleSheet.create({
  page: {
    
    fontSize: 12,
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  image: {
    width: 50,
    height: 50,
    borderRadius: 10,
  },
  table: {
    display: 'table',
    width: 'auto',
    borderWidth: 1,
    borderColor: '#07223D',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomColor: '#CCCCCC',
    borderBottomWidth: 1,
    alignItems: 'center',
    
  },
  tableColHeader: {
    width: '25%',
    borderRightColor: '#CCCCCC',
    borderRightWidth: 1,
    padding: 5,
    backgroundColor: '#f2f2f2',
  },
  tableCol: {
    width: '25%',
    borderRightColor: '#CCCCCC',
    borderRightWidth: 1,
    padding: 5,
  },
  tableCell: {
    margin: 'auto',
    marginTop: 5,
  },
  header: {
    fontSize: 24,
    textAlign: 'center',
    color: 'black',
    marginBottom: 20,
  },
  text: {
    margin: 12,
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: 'Poppins',
  },
  footer: {
    position: 'absolute',
    fontSize: 12,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
});

// Component to render the PDF document
const ReportDocument = ({ inventory }) => (
  <Document>
    <Page style={styles.page}>
      <Text style={styles.header}>Inventory Report</Text>
      <View style={styles.table}>
        {/* Table Header */}
        <View style={styles.tableRow}>
          <Text style={styles.tableColHeader}>Image</Text>
          <Text style={styles.tableColHeader}>Name</Text>
          <Text style={styles.tableColHeader}>Category</Text>
          <Text style={styles.tableColHeader}>Stock Level</Text>
        </View>
        {/* Rows with Inventory Data */}
        {inventory.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Image style={[styles.tableCol]} src={item.imageUrl} />
            <Text style={[styles.tableCol, styles.tableCell]}>{item.name}</Text>
            <Text style={[styles.tableCol, styles.tableCell]}>{item.category}</Text>
            <Text style={[styles.tableCol, styles.tableCell]}>{item.stockLevel}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>Generated by Well Worn SL</Text>
    </Page>
  </Document>
);

export default ReportDocument;
